<!DOCTYPE html>
<html lang="en">
<head>
    <title>Calculator</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../style/styles.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>


<div class="container-fluid">
    <div class="row">
        <div class="nav" id="navBar">
            <div id="navBarText">
                <p class="navbar-text navbar-center">LinkedIn: <a href="https://www.linkedin.com/in/haslett-anthony/"
                                                                 class="navbar-link">Anthony Haslett</a></p>
                <p class="navbar-text navbar-center">GitHub: <a href="https://github.com/AnthonyHaslett"
                                                               class="  navbar-link">See this project on GitHub</a></p>
            </div>
        </div>
    </div>
</div>



    <div class="container">